#mysql
spring:
    datasource:
        #MySQL配置
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/staffing?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.xxx.entity
    # 打印所执行的sql语句。引入mybatis-plus后管理属于mybatis_plus，需要到mybatis_plus中配置
#    configuration:
#        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 打印操作数据库的日志
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
    #修改端口号
    port: 9090

files:
    upload:
        path: D:\Code\GraduationProject\files\
